# Generated by Django 3.1.6 on 2021-02-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='', max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
